platform :ios, '7.0'  
pod 'AFNetworking', '~> 2.0'
pod 'TouchJSON', '~> 1.1'
pod 'OpenUDID', '~> 1.0.0'
pod 'ZipArchive', '~> 1.4.0'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'MDRadialProgress', '~> 1.3.2'
pod 'SDWebImage', '~>3.7'
pod 'JTSlideShadowAnimation', '~> 1.0'
pod 'SMPageControl', '~> 1.2'